#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "asciidoctorj"
        versions:
          - "2.x"
      - dependency-name: "hibernate-validator"
        versions:
          - "8.x"
      # asciidoctorj new version needs higher swagger2markup, which will need java11
      - dependency-name: "jakarta.activation"
        versions:
          - "2.x"
      - dependency-name: "jakarta.servlet-api"
        versions:
          - "5.x"
          - "6.x"
      - dependency-name: "jakarta.ws.rs-api"
        versions:
          - "3.x"
      - dependency-name: "jersey"
        versions:
          - "3.x"
      - dependency-name: "jersey-client"
        versions:
          - "3.x"
      - dependency-name: "jersey-common"
        versions:
          - "3.x"
      - dependency-name: "logback-classic"
        # logback new versions needs java11 now
      - dependency-name: "logback-core"
        # logback new versions needs java11 now
      - dependency-name: "protostuff-parser"
        # protostuff-parser new versions needs java11 now
      - dependency-name: "swagger2markup"
        # swagger2markup new version needs java11 now
