# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: helloworld.Greeter
  version: 1.0.0
  x-java-interface: com.huawei.paas.cse.demo.helloworld.greeter.Hello

# the domain of the service
#host: api.uber.com

# array of all schemes that your API supports
#schemes:
#  - https

# will be prefixed to all paths
basePath: /pojo/rest/helloworld.Greeter
produces:
  - application/json

paths:
  /SayHello:
    post:
      operationId: SayHello
      parameters:
        - name: name
          in: body
          required: true
          schema:
            type: string
      responses: 
        200:
          description: asdf
          schema:
            type: string
        default:
          description: asf
          schema:
            type: string
  /SayHelloAgain:
    post:
      operationId: SayHelloAgain
      parameters:
        - name: name
          in: body
          required: true
          schema:
            type: string
      responses: 
        200:
          description: asdf
          schema:
            type: string
        default:
          description: asf
          schema:
            type: string