# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: smartcare test
  version: 1.0.0
  x-java-interface: com.huawei.paas.cse.demo.smartcare.SmartCare

# the domain of the service
#host: api.uber.com

# array of all schemes that your API supports
#schemes:
#  - https

# will be prefixed to all paths
basePath: /pojo/rest/plat/meta/v1
produces:
  - application/json

paths:
  /applications:
    post:
      operationId: addApplication
      parameters:
        - name: application
          in: body
          required: true
          schema:
            $ref: '#/definitions/Application'
      responses:
        201:
          description: success
          schema:
            $ref: '#/definitions/Response'
        400:
          description: error
          schema:
            $ref: '#/definitions/Response'
        500:
          description: error
          schema:
            $ref: '#/definitions/Response'

  /applications/{appName}:
    delete:
      operationId: delApplication
      parameters:
        - name: appName
          in: path
          required: true
          type: string
      responses:
        201:
          description: success
          schema:
            $ref: '#/definitions/Response'
        400:
          description: error
          schema:
            $ref: '#/definitions/Response'
        500:
          description: error
          schema:
            $ref: '#/definitions/Response'


definitions:
  Application:
    type: object
    properties:
      name:
        type: string
      labelEN:
        type: string
      labelCH:
        type: string
      defaultGroup:
        type: string
      version:
        type: string
      dynamicFlag:
        type: boolean
      groups:
        type: array
        items:
          $ref: '#/definitions/Group'
    required:
      - name
      - defaultGroup
      - version
      - dynamicFlag
      - groups

  Group:
    type: object
    properties:
      name:
        type: string
      labelEN:
        type: string
      labelCH:
        type: string
    required:
      - name

  Response:
    type: object
    x-java-class: com.huawei.paas.cse.demo.smartcare.Response
    properties:
      resultCode:
        type: integer
        format: int32
      resultMessage:
        type: string
    required:
      - resultCode

