name: "Question"
description: "Ask a question or seek help"
labels: ["question"]
body:
  - type: "markdown"
    attributes:
      value: "### Question\nPlease describe your question."
  - type: "markdown"
    attributes:
      label: "What are you trying to achieve?"
      description: "Provide context on what you're trying to do."
      placeholder: "e.g., I'm trying to integrate this project with X..."
  - type: "markdown"
    attributes:
      label: "Have you checked the documentation?"
      description: "Please confirm if you've already checked the documentation for the answer."
      placeholder: "e.g., Yes, I checked the installation guide..."