## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------

openapi: 3.0.1
info:
  title: swagger definition for org.apache.servicecomb.demo.pojo.server.TestImpl
  version: 1.0.0
servers:
- url: /TestImpl
paths:
  /addString:
    post:
      operationId: addString
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addStringBody'
        x-name: addStringBody
      responses:
        "200":
          description: response of 200
          content:
            application/json:
              schema:
                type: string
  /getTestString:
    post:
      operationId: getTestString
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getTestStringBody'
        x-name: getTestStringBody
      responses:
        "200":
          description: response of 200
          content:
            application/json:
              schema:
                type: string
  /patchTestStatic:
    post:
      operationId: patchTestStatic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/patchTestStaticBody'
        x-name: patchTestStaticBody
      responses:
        "200":
          description: response of 200
          content:
            application/json:
              schema:
                type: string
  /postTestStatic:
    post:
      operationId: postTestStatic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postTestStaticBody'
        x-name: postTestStaticBody
      responses:
        "200":
          description: response of 200
          content:
            application/json:
              schema:
                type: string
  /splitParam:
    post:
      operationId: splitParam
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/splitParamBody'
        x-name: splitParamBody
      responses:
        "200":
          description: response of 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /testException:
    post:
      operationId: testException
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/testExceptionBody'
        x-name: testExceptionBody
      responses:
        "200":
          description: response of 200
          content:
            application/json:
              schema:
                type: string
  /testStringArray:
    post:
      operationId: testStringArray
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/testStringArrayBody'
        x-name: testStringArrayBody
      responses:
        "200":
          description: response of 200
          content:
            application/json:
              schema:
                type: string
  /testTraceId:
    post:
      operationId: testTraceId
      responses:
        "200":
          description: response of 200
          content:
            application/json:
              schema:
                type: string
  /wrapParam:
    post:
      operationId: wrapParam
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestRequest'
        x-name: request
      responses:
        "200":
          description: response of 200
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    addStringBody:
      type: object
      properties:
        strArr:
          type: array
          items:
            type: string
    getTestStringBody:
      type: object
      properties:
        code:
          type: string
    patchTestStaticBody:
      type: object
      properties:
        code:
          type: integer
          format: int32
    postTestStaticBody:
      type: object
      properties:
        code:
          type: integer
          format: int32
    User:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
        index:
          type: integer
          format: int32
        names:
          type: array
          items:
            type: string
      x-java-class: org.apache.servicecomb.demo.server.User
    splitParamBody:
      type: object
      properties:
        index:
          type: integer
          format: int32
        user:
          $ref: '#/components/schemas/User'
    testExceptionBody:
      type: object
      properties:
        code:
          type: integer
          format: int32
    testStringArrayBody:
      type: object
      properties:
        arr:
          type: array
          items:
            type: string
    TestRequest:
      type: object
      properties:
        index:
          type: integer
          format: int32
        user:
          $ref: '#/components/schemas/User'
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
        data:
          type: string
          format: byte
      x-java-class: org.apache.servicecomb.demo.server.TestRequest
