## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------

# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: cse test
  version: 1.0.0
  x-java-interface: org.apache.servicecomb.demo.tccserver.TestTcc
  
# the domain of the service
#host: api.uber.com

# array of all schemes that your API supports
#schemes:
#  - https

# will be prefixed to all paths
basePath: /pojo/rest/tcc-server
produces:
  - application/json
  
paths:
  /splitParam:
    post:
      operationId: splitParam
      parameters:
        - name: index
          in: query
          required: true
          type: number
        - name: user
          in: body
          schema:
            $ref: '#/definitions/User'
      responses: 
        "200":
          description: asdf
          schema: 
            $ref: '#/definitions/User'
        default:
          description: asf
          schema:
            $ref: '#/definitions/Error'
  /wrapParam:
    post:
      operationId: wrapParam
      parameters:
        - name: TestRequest
          in: body
          required: true
          schema: 
            $ref: '#/definitions/TestRequest'
      responses: 
        "200":
          description: asdf
          schema: 
            $ref: '#/definitions/User'
        default:
          description: asf
          schema:
            $ref: '#/definitions/Error'
            
definitions:
  Error:
    type: object
    x-java-class: org.apache.servicecomb.core.exception.CommonExceptionData
    properties:
      message:
        type: string
  TestRequest:
    type: object
    properties:
      index:
        type: number
      user:
        $ref: '#/definitions/User'
      users:
        type: array
        items:
          $ref: '#/definitions/User'
      data:
        type: string
        format: byte
  User:
    type: object
    properties:
      name:
        type: string
      age:
        type: number
      index:
        type: number
